# statsmodel para regresión lineal

In [1]:
import pandas as pd

data = pd.read_csv('datasets/ads/Advertising.csv')
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [14]:
import statsmodels.formula.api as smf
lm = smf.ols(formula='Sales~TV', data=data).fit()

In [15]:
lm.params

Intercept    7.032594
TV           0.047537
dtype: float64

Modelo lineal predictivo sería: Sales= 7.032594 + 0.047537 * TV

In [16]:
lm.pvalues

Intercept    1.406300e-35
TV           1.467390e-42
dtype: float64

In [17]:
lm.rsquared

0.611875050850071